### ISSUE TITLE
BeamSQL on Nemo 문제 발생

### ISSUE THREAD

**Issue by tantara** [swsnu/bd2018#17]
beam sql 사용하는 숙제에서 
spark에서는 결과가 잘 나오는데 nemo에서는 아래와 같은 에러가 발생하면서 종료됩니다.

beam sql 사용하지 않는 코드는 문제 없이 동작합니다.

프로젝트 repo 입니다. [tantara/bd18f-taekmin-kim](https://github.com/tantara/bd18f-taekmin-kim/tree/master/hw1_beam)

```
 WARN 11-01 21:17:36,768 Pipeline:585 [main] - The following transforms do not have stable unique names: HomeworkBaseball.ParseCSVLinesAsRow, TextIO.Read, SqlTransform
 INFO 11-01 21:17:37,303 JobLauncher:189 [main] - Waiting for the driver to be ready
 INFO 11-01 21:17:37,303 JobLauncher:197 [main] - Launching DAG...
 INFO 11-01 21:17:37,453 JobLauncher:210 [main] - Waiting for the DAG to finish execution
Nov 01, 2018 9:17:45 PM org.apache.reef.runtime.common.launch.REEFUncaughtExceptionHandler uncaughtException
심각: Thread RuntimeMaster thread threw an uncaught exception.
org.apache.nemo.common.exception.UnrecoverableFailureException: java.lang.Exception: The plan failed on Stage7-0-0 in Executor1
	at org.apache.nemo.runtime.master.scheduler.BatchScheduler.onTaskStateReportFromExecutor(BatchScheduler.java:195)
	at org.apache.nemo.runtime.master.RuntimeMaster.handleControlMessage(RuntimeMaster.java:370)
	at org.apache.nemo.runtime.master.RuntimeMaster.access$100(RuntimeMaster.java:76)
	at org.apache.nemo.runtime.master.RuntimeMaster$MasterControlMessageReceiver.lambda$onMessage$45(RuntimeMaster.java:331)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: The plan failed on Stage7-0-0 in Executor1
	... 7 more
```

**Comment by johnyangk** [comment]
Caused by: java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.sha1Hex(Ljava/lang/String;)Ljava/lang/String;
  at edu.snu.bd.examples.HomeworkBaseball$HashFn.apply(HomeworkBaseball.java:110)
  ... 82 more

Root cause는 위와 같습니다.
제 생각에는 여러 dependency들 간의 conflict (e.g., version conflict) 인 것 같습니다.

pom.xml에서 nemo-runner profile은 기존 skeleton과 동일하게 하고, dependencies 부분에 사용하실 library만 (dependency가 적은) 설정하시면 해결할 수 있을 것 같습니다.

**Comment by johnyangk** [comment]
#18 이와 관련하여 공지하였습니다.
